# Generated by Django 4.2.28 on 2026-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="recording",
            field=models.FileField(
                blank=True, null=True, upload_to="recordings/%Y/%m/"
            ),
        ),
    ]
