# Generated by Django 4.2.28 on 2026-03-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0002_add_recording_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="rubric_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"tone": 8, "rhythm": 7, "technique": 9, "expression": 8}',
            ),
        ),
    ]
