# Generated by Django 4.2.28 on 2026-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_assignmentsubmission_rubric_scores"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["academy", "student", "status"],
                name="enrollments_academy_d488e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="enrollments_student_885f1d_idx"
            ),
        ),
    ]
