# Generated by Django 4.2.28 on 2026-03-06 22:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_enrollment_enrollments_academy_d488e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file_upload",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_private_storage,
                upload_to=apps.common.storage.upload_to_submissions,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="recording",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_private_storage,
                upload_to=apps.common.storage.upload_to_recordings,
            ),
        ),
    ]
