# Generated by Django 4.2.28 on 2026-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_timezone_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
