# Generated by Django 4.2.28 on 2026-03-03 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_email_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
