# Generated by Django 4.2.28 on 2026-03-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_parent_user_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_calendar_token",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="ical_feed_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
