# Generated by Django 4.2.28 on 2026-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_google_calendar_token_user_ical_feed_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
