# Generated by Django 4.2.28 on 2026-03-06 22:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_public_storage,
                upload_to=apps.common.storage.upload_to_avatars,
            ),
        ),
    ]
