# Generated by Django 4.2.28 on 2026-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_coppa_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("removed", "Removed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
