# Generated by Django 4.2.28 on 2026-02-28 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300)),
                ("description", models.TextField()),
                (
                    "instrument",
                    models.CharField(
                        help_text="e.g. Piano, Guitar, Vocals", max_length=50
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, help_text="e.g. Classical, Jazz", max_length=50
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("prerequisites", models.TextField(blank=True)),
                ("learning_outcomes", models.JSONField(default=list)),
                ("estimated_duration_weeks", models.PositiveIntegerField(default=8)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_thumbnails/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("max_students", models.PositiveIntegerField(default=30)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("academy", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Lesson content in Markdown"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Link to pre-recorded video"),
                ),
                ("sheet_music_url", models.URLField(blank=True)),
                ("audio_example_url", models.URLField(blank=True)),
                (
                    "topics",
                    models.JSONField(
                        default=list, help_text='e.g. ["Major Scales","Sight Reading"]'
                    ),
                ),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=30)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice Piece"),
                            ("theory", "Music Theory Exercise"),
                            ("ear_training", "Ear Training"),
                            ("composition", "Composition / Arrangement"),
                            ("performance", "Performance Recording"),
                            ("technique", "Technique Drill"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("piece_title", models.CharField(blank=True, max_length=200)),
                ("composer", models.CharField(blank=True, max_length=200)),
                ("tempo_bpm", models.PositiveIntegerField(blank=True, null=True)),
                ("practice_minutes_target", models.PositiveIntegerField(default=30)),
                ("reference_audio_url", models.URLField(blank=True)),
                ("sheet_music_url", models.URLField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "created_at"],
            },
        ),
    ]
