# Generated by Django 4.2.28 on 2026-03-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_lessonattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisite_courses",
            field=models.ManyToManyField(
                blank=True, related_name="dependent_courses", to="courses.course"
            ),
        ),
    ]
