# Generated by Django 4.2.28 on 2026-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_prerequisite_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="course",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=0, help_text="Price in cents. 0 = free course."
            ),
        ),
    ]
