# Generated by Django 4.2.28 on 2026-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_currency_course_price_cents"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["academy", "is_published"],
                name="courses_cou_academy_a1c896_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "academy"], name="courses_cou_instruc_ec24d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "order"], name="courses_les_course__dc0bc6_idx"
            ),
        ),
    ]
