# Generated by Django 4.2.28 on 2026-03-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_courses_cou_academy_a1c896_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="Template courses can be cloned by any academy as a starting point.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template course this was cloned from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloned_courses",
                to="courses.course",
            ),
        ),
    ]
