# Generated by Django 4.2.28 on 2026-03-06 22:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_add_template_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_public_storage,
                upload_to=apps.common.storage.upload_to_course_thumbnails,
            ),
        ),
        migrations.AlterField(
            model_name="lessonattachment",
            name="file",
            field=models.FileField(
                storage=apps.common.storage.get_private_storage,
                upload_to=apps.common.storage.upload_to_lesson_attachments,
            ),
        ),
    ]
