# Generated by Django 4.2.28 on 2026-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_r2_storage_backends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Lesson content in HTML (edited via TinyMCE rich text editor)",
            ),
        ),
    ]
