# Generated by Django 4.2.28 on 2026-03-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academies", "0004_r2_storage_backends"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("member_invited", "Member Invited"),
                            ("member_accepted", "Member Accepted"),
                            ("member_removed", "Member Removed"),
                            ("role_changed", "Role Changed"),
                            ("course_published", "Course Published"),
                            ("course_unpublished", "Course Unpublished"),
                            ("session_cancelled", "Session Cancelled"),
                            ("session_rescheduled", "Session Rescheduled"),
                            ("refund_requested", "Refund Requested"),
                            ("refund_processed", "Refund Processed"),
                            ("settings_updated", "Settings Updated"),
                            ("price_changed", "Price Changed"),
                            ("seat_limit_hit", "Seat Limit Reached"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name, e.g. 'membership', 'course', 'session'",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="PK of the affected entity", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable summary of what happened"
                    ),
                ),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=36)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for platform-level events",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="academies.academy",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-triggered actions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["academy", "-created_at"],
                        name="common_audi_academy_ccf2f6_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="common_audi_action_44153b_idx",
                    ),
                ],
            },
        ),
    ]
