# Generated by Django 4.2.28 on 2026-03-03 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0002_announcement"),
        ("courses", "0003_course_prerequisite_courses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarTrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("interval", "Interval Recognition"),
                            ("chord", "Chord Identification"),
                            ("rhythm", "Rhythm Dictation"),
                            ("melody", "Melody Dictation"),
                            ("scale", "Scale Identification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("difficulty", models.PositiveIntegerField(default=1, help_text="1-5")),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="List of question objects with answer/options",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise_type", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="RecitalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("jitsi_room_name", models.CharField(max_length=255, unique=True)),
                ("recording_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="RecordingArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("recording", models.FileField(upload_to="student_recordings/%Y/%m/")),
                ("instrument", models.CharField(blank=True, max_length=50)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecitalPerformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("piece_title", models.CharField(max_length=300)),
                ("composer", models.CharField(blank=True, max_length=200)),
                ("performance_order", models.PositiveIntegerField(default=0)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "recital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performers",
                        to="music_tools.recitalevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recital_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["performance_order"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.FileField(
                        blank=True, null=True, upload_to="analysis/%Y/%m/"
                    ),
                ),
                ("recording_url", models.URLField(blank=True)),
                (
                    "analysis_result",
                    models.JSONField(
                        default=dict,
                        help_text='e.g. {"pitch_accuracy": 85, "rhythm_accuracy": 90, "tempo_stability": 78}',
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EarTrainingScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveIntegerField()),
                ("total_questions", models.PositiveIntegerField()),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="music_tools.eartrainingexercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ear_training_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
