# Generated by Django 4.2.28 on 2026-03-06 22:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practiceanalysis",
            name="recording",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_private_storage,
                upload_to=apps.common.storage.upload_to_analysis,
            ),
        ),
        migrations.AlterField(
            model_name="recordingarchive",
            name="recording",
            field=models.FileField(
                storage=apps.common.storage.get_private_storage,
                upload_to=apps.common.storage.upload_to_student_recordings,
            ),
        ),
    ]
