# Generated by Django 4.2.28 on 2026-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="practicelog",
            index=models.Index(
                fields=["student", "date"], name="practice_pr_student_b66b09_idx"
            ),
        ),
    ]
