# Generated by Django 4.2.28 on 2026-03-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livesession",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
