# Generated by Django 4.2.28 on 2026-03-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_instructoravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="external_meeting_url",
            field=models.URLField(
                blank=True, help_text="Zoom/Meet URL if not using Jitsi"
            ),
        ),
        migrations.AddField(
            model_name="livesession",
            name="video_platform",
            field=models.CharField(
                choices=[
                    ("jitsi", "Jitsi Meet"),
                    ("zoom", "Zoom"),
                    ("google_meet", "Google Meet"),
                    ("custom", "Custom URL"),
                ],
                default="jitsi",
                max_length=20,
            ),
        ),
    ]
