# Generated by Django 4.2.28 on 2026-03-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_rename_jitsi_to_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="recording_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "Not Requested"),
                    ("recording", "Recording"),
                    ("processing", "Processing"),
                    ("available", "Available"),
                    ("failed", "Failed"),
                ],
                default="not_requested",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="livesession",
            name="rescheduled_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original session this was rescheduled from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_to",
                to="scheduling.livesession",
            ),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("open_for_join", "Open for Joining"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                    ("no_show_instructor", "No-Show (Instructor)"),
                    ("no_show_student", "No-Show (Student)"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
