# Generated by Django 4.2.29 on 2026-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_add_message_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "New Enrollment"),
                    ("session_reminder", "Session Reminder"),
                    ("session_cancelled", "Session Cancelled"),
                    ("assignment_due", "Assignment Due"),
                    ("assignment_graded", "Assignment Graded"),
                    ("invitation", "Academy Invitation"),
                    ("session_booked", "Session Booked"),
                    ("session_rescheduled", "Session Rescheduled"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
