# Generated by Django 4.2.28 on 2026-02-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="academy_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("max_students", models.PositiveIntegerField(default=100)),
                ("max_instructors", models.PositiveIntegerField(default=10)),
                (
                    "primary_instruments",
                    models.JSONField(
                        default=list,
                        help_text='Instruments taught, e.g. ["Piano","Guitar","Violin"]',
                    ),
                ),
                (
                    "genres",
                    models.JSONField(
                        default=list,
                        help_text='Genres offered, e.g. ["Classical","Jazz","Rock"]',
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "academies",
                "ordering": ["name"],
            },
        ),
    ]
