# Generated by Django 4.2.28 on 2026-03-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("academies", "0002_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"practice_logs": true, "ear_training": false, "recordings": true}',
            ),
        ),
        migrations.AddField(
            model_name="academy",
            name="primary_color",
            field=models.CharField(
                default="#6366f1", help_text="Hex color code", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="academy",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academies",
                to="payments.academytier",
            ),
        ),
        migrations.AddField(
            model_name="academy",
            name="welcome_message",
            field=models.TextField(
                blank=True, help_text="Shown on branded signup page"
            ),
        ),
    ]
