# Generated by Django 4.2.28 on 2026-03-06 22:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academies",
            "0003_academy_features_academy_primary_color_academy_tier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_public_storage,
                upload_to=apps.common.storage.upload_to_academy_logos,
            ),
        ),
    ]
